# Generated by Django 4.0.7 on 2024-04-09 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.PositiveBigIntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('department', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('emp_id', models.CharField(max_length=50, null=True)),
                ('grant', models.BooleanField(default=False, null=True)),
                ('revoke', models.BooleanField(default=False, null=True)),
                ('accept', models.BooleanField(default=False, null=True)),
                ('decline', models.BooleanField(default=False, null=True)),
                ('admit', models.BooleanField(default=False, null=True)),
                ('deny', models.BooleanField(default=False, null=True)),
            ],
        ),
    ]
